<?php

namespace Core\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends EntityRepository
{
	public function getUserDocs($userId)
	{
		$qb = $this->createQueryBuilder('D')
			->select('D')
			->where('D.user = :userId')
			->orderBy('D.folderName')
			->setParameter('userId', $userId);

		return $qb->getQuery()->getResult();
	}
}
